イベント詳細画面に遷移できるようにしました
ikkei1616/watnowseikabutusite pull request #11
Opened 2024-08-02 14:57 UTC by valen0306

## 実装内容
   - イベント一覧画面からそれぞれのevent_idごとにイベント詳細画面に遷移できるようにした
## 関連issue
   - #2
## 特にみて欲しい部分
   - データがない時の遷移も作っときました
## 今回作れなかった部分
   - DB設計上の編集(リンク)
## 補足
   - event_id=2のリンクを踏んだ時の遷移
   <img src="https://github.com/user-attachments/assets/b8c79ba2-ac79-45eb-990b-09ef3e34ef00" width="250">

   - event_id=5のリンクを踏んだ時の遷移(event_id=5はmockデータで定義してません)
   <img src="https://github.com/user-attachments/assets/2c8a8ff2-47e6-4f9f-a16a-1b489e4e179a" width="250">

- event_id=5の挙動を確認するために./events/page.tsxのファイルも編集してあります

2024-08-05 05:51 UTC, YukaChoco reviewed
ちょっとだけ修正お願いします！

2024-08-06 05:41 UTC, YukaChoco requested changes
動作自体はOKそう！
後少しだけ修正お願いします！

2024-08-06 05:41 UTC, YukaChoco commented on src/app/events/[event_id]/LoadingSpinner.tsx
> +export default LoadingSpinner;
この `LoadingSpinner.tsx` は他の画面でも共通で使いそうだから、`LoadingSpinner.module.css` と一緒に `app` フォルダと同じところに `components` フォルダを用意してそこに入れようか

⬇️みたいな感じ

```
src
|-- app
    |-- events
    |-- new
    |-- page.tsx
|-- components
    |-- LoadingSpiner.tsx
    |-- LoadingSpinner.module.css
```

2024-08-06 05:41 UTC, YukaChoco commented on src/app/events/[event_id]/page.tsx
> +    debugger
デバッグ用のコードは基本的に削除してからpushすると後に残らないので消してもらえるとbetter◎

2024-08-06 16:23 UTC, valen0306 commented on src/app/events/[event_id]/page.tsx
> +    debugger
修正しました

2024-08-06 16:23 UTC, valen0306 commented on src/app/events/[event_id]/LoadingSpinner.tsx
> +export default LoadingSpinner;
修正しました

2024-08-06 16:30 UTC, YukaChoco approved these changes
LGTM！
修正たくさんお疲れ様でした！

2024-08-06 16:32 UTC, merged