htmlの日本語設定とOGPの設定を追加しました
ikkei1616/watnowseikabutusite pull request #33
Opened 2024-08-22 08:13 UTC by valen0306

## 実装内容
   - htmlの日本語設定とOGPの設定を追加しました
## 関連issue
   - #30 
   - #31 
## 結果画像
   - 特になし
## 特にみて欲しい部分
   - 特になし
## 今回作れなかった部分
   - 特になし
## 補足
   - 今後追加の可能性あり

2024-08-22 18:17 UTC, YukaChoco requested changes
夜中にすみません、変更依頼です！

2024-08-22 18:17 UTC, YukaChoco commented on src/app/layout.tsx
> +  description: "Watnowの成果物一覧サイト",
watnowの表記は全部小文字です！

2024-08-22 18:17 UTC, YukaChoco commented on src/app/layout.tsx
> +  title: "WatBox",
大文字小文字問題は明日決めましょう

2024-08-26 15:13 UTC, valen0306 commented
OGPの小文字設定について修正しました！

2024-08-27 04:51 UTC, YukaChoco approved these changes
LGTM!!

2024-08-27 04:51 UTC, merged