サービス作成フォーム制作
ikkei1616/watnowseikabutusite pull request #36
Opened 2024-08-23 08:22 UTC by kotarowakuwaku

## 実装内容
   - サービス作成フォーム
## 関連issue
   - #26 
## 結果画像
   - 
## 特にみて欲しい部分
   - 
## 今回作れなかった部分
   - 
## 補足
   - まだ全然途中です。
   - react-hook-form, zod を使ってるので使い方を見たい方は見て下さい

2024-08-27 04:42 UTC, YukaChoco commented
見たことないコードしてる、、、、、笑
出来上がったらレビュー頑張ります

2024-08-31 13:33 UTC, YukaChoco commented
ほんとごめんレビューのやる気がかなり落ちてる笑

2024-08-31 13:47 UTC, YukaChoco requested changes
とりあえず、まず、めっちゃエラー吐いてるんでちゃんと直してください笑笑
(全部写ってないから、手元の開発者ツールで確認してね)

<img width="500" alt="スクリーンショット 2024-08-31 22 35 50" src="https://github.com/user-attachments/assets/011294f4-1508-4e50-a73f-a44d31a4fa6a">

```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.
```
↑このエラーに関しては、before,after見たいので、直したやつだけでコミットしてもらえると私が喜ぶ

2024-08-31 13:47 UTC, YukaChoco commented on src/app/services/page.tsx
> +export default page
シンプルすぎてじわった
これなら別に今作らんでもよかろう笑笑

2024-08-31 13:47 UTC, YukaChoco commented on src/app/services/new/page.tsx
> +          ))
`.map` するときは一番親の要素に一意に認識できる `key` が必須です

2024-08-31 13:47 UTC, YukaChoco commented on src/app/services/new/hooks.ts
> +    {value: "years", label: "years"},
`label` は日本語にしようか。
UIはfigmaの
`1` `月` 間
ってやつになるようにしてください！

2024-08-31 13:49 UTC, YukaChoco commented
@kotarowakuwaku 
もし可能なら、実際にsupabaseのデータをとってきて
- イベントの選択
- 賞の選択
までできるようになってるとすごい嬉しいな

あと、使用技術・作成者の複数選択もかなり大変になりそうだから、react-hook-form・zodで実装できるか不安だけど、figmaのUI見つつ試してみてもらえると、、、！

2024-09-10 15:37 UTC, kotarowakuwaku commented
明日はデザイン調整

2024-10-06 06:53 UTC, YukaChoco approved these changes
脳死LGTM
- 新規作成後の画面遷移を `/admin/services` に変更だけお願いします！

余裕があったらこういうのしてもいいかもね
- enum使ってInputTypeとかにする(説明済み)
- `releaseMonth` とかは `const.ts` とかに分けると better?

2024-10-06 08:12 UTC, merged