イベントページに賞の登録機能を追加
ikkei1616/watnowseikabutusite pull request #37
Opened 2024-08-25 09:10 UTC by valen0306

## 実装内容
   - イベント新規登録ページで賞を登録できるようにした
   - イベント編集ページで賞を編集できるようにした
   - イベント詳細ページで賞に関する情報を閲覧できるようにした
   - 賞に関する型定義の追加
   - supabaseのawardsテーブルのpolicyを追加
## 関連issue
   - #34 
## 結果画像
 - イベント詳細ページ(変更前)
   <img src="https://github.com/user-attachments/assets/e814ff32-1005-4b38-9e4f-c182e1b07cfc" width="250">

- イベント編集ページ(ハーゲンダッツ賞を削除時)
  <img src="https://github.com/user-attachments/assets/8ccb0a44-917a-4bd5-9561-43b7ae9998b3" width="250">

- イベント編集ページ(アイスクリーム賞を追加時)
  <img src="https://github.com/user-attachments/assets/2962bbf6-7fb0-4fc9-8082-3c5b85491f70" width="250">

- イベント新規登録画面
  <img src="https://github.com/user-attachments/assets/c732e22f-4a7a-4db4-955b-e7d96f8d8380" width="250">

## 特にみて欲しい部分
   - イベント編集画面、新規登録画面で賞を登録するとき、バグが発生しないように賞の表示順が登録者によって打ち込めないようになっています。賞を削除するとき、それまでに登録された賞の一番後ろに賞を追加するときは特に問題ないんですけど、すでに賞が登録された状態で表示順が1(order_num=1)の場所に登録しようとした場合とかに少しめんどくさい作業をする必要があります。(少しめんどくさい作業があるだけで普通に使えますが)この部分についてはのちのち変更が必要かもです。
## 今回作れなかった部分
   - 上に書いた内容です
## 補足
   -

2024-08-26 01:43 UTC, YukaChoco commented
@valen0306 

> 賞を削除するとき、それまでに登録された賞の一番後ろに賞を追加するときは特に問題ないんですけど、すでに賞が登録された状態で表示順が1(order_num=1)の場所に登録しようとした場合とかに少しめんどくさい作業をする必要があります。

これが理解できていなくて、どういう意味でしょうか😭

2024-08-26 02:07 UTC, valen0306 commented
わかりにくくてごめんなさい！
賞を追加するボタンを押したときに、新しいフォームがこれまで登録されている賞の一番後ろに追加されます(これまで賞を2つ登録している場合を考えます。賞を追加するボタンを押した際に表示順が3のところにしか入力フォームを追加することができません。)これだとこれまで入力されたものを残したまま先頭に賞を追加したい場合にそれまで登録した賞をずらす作業が必要になります。(これまで賞を2つ登録している場合を考えます。登録者は表示順1のところに新しく賞を追加し、これまで登録されていた2つの賞を表示順2,3のところにずらしたいとします。この時登録者は賞を追加するボタンで表示順3のところにフォームを追加し、表示順1,2に登録されている賞を表示順2,3に再度登録した上で表示順1に新しい賞を追加するという作業が必要になります。)これがちょっとめんどくさいってことです。

2024-08-26 02:10 UTC, YukaChoco commented
確かに今のままだとそうするしかなさそうね。
上下の矢印ボタンを追加して順番を入れ替える処理を加えてみるのはどうだろう？

2024-08-26 02:16 UTC, valen0306 commented
それありですね！
ただ、今回のサイトの場合、賞の登録が多くて3,4つくらいになりそうかなとも思っていて、この作業がそこまでめんどくさくないかなと。あんまり機能もりもりにすると逆にわかりずらいかなとも思うんですが、どうですか？

2024-08-26 02:21 UTC, YukaChoco requested changes
いくつか修正お願いします！

全体的なレビューもすると、賞を増やしすぎると、画面外にはみ出してしまっているので、そこも修正お願いします！
<img width="1470" alt="スクリーンショット 2024-08-26 11 11 29" src="https://github.com/user-attachments/assets/49baf437-ccf2-4501-b514-3764c6b2572b">

あと、GitHubに上げる前に、「ドキュメントのフォーマットを揃える」のを習慣づけるとBetterかも！VSCode上で右クリしたら出てくるはず！
VSCodeの設定をいじれば、保存時にフォーマットを揃えるとかもできるので、調べてみて〜

2024-08-26 02:21 UTC, YukaChoco commented on src/app/events/[event_id]/edit/page.tsx
> +              />
requiredにはなってるんだけど、入力せずとも登録できてしまうらしい
ちょっとぱっと見じゃ理由わからないから、原因は自分で調べてみておくれ
<img width="1470" alt="スクリーンショット 2024-08-26 11 12 21" src="https://github.com/user-attachments/assets/97867ec6-a819-45ce-a32e-1e44d2344b82">

2024-08-26 02:33 UTC, YukaChoco commented
> それありですね！
> ただ、今回のサイトの場合、賞の登録が多くて3,4つくらいになりそうかなとも思っていて、この作業がそこまでめんどくさくないかなと。あんまり機能もりもりにすると逆にわかりずらいかなとも思うんですが、どうですか？

確かに、納得はできるかな。
入力内容が複数あるとすれば(例えば賞を受け取れる人数、賞金・賞品など)、入れ替えるのが大変になってくるのだけれど、今回は名称だけなので入れ替えもコピペで済むし、いいと思う🙆‍♀️

2024-08-26 04:22 UTC, valen0306 commented on src/types/Event.ts
>  }
EventDetailの中でawardsは定義しないっていう解釈であってますか？

2024-08-26 04:27 UTC, YukaChoco commented on src/types/Event.ts
>  }
`award.ts` を別に作る認識です！！！！！

2024-08-26 04:28 UTC, YukaChoco commented on src/types/Event.ts
>  }
別ファイルで定義したのちに `import` して使ってください

2024-08-26 05:08 UTC, valen0306 commented on src/types/Event.ts
>  }
了解です！

2024-08-26 13:01 UTC, valen0306 commented on src/app/events/[event_id]/edit/page.tsx
> +              />
今のところ原因がわからず、、、
ReactHookFormをいれるときになおってほしい、、、
今後要修正！

2024-08-26 15:07 UTC, valen0306 commented
今すぐに変更が必要なところについて修正しました！
レビューお願いします！！

2024-08-27 04:41 UTC, YukaChoco approved these changes
動作確認OK！
LGTMです！！

2024-08-27 04:51 UTC, merged