watnowユーザーが利用するページとそれ以外のユーザーが利用するページをわけました
ikkei1616/watnowseikabutusite pull request #40
Opened 2024-08-27 09:25 UTC by valen0306

## 実装内容
   - adminディレクトリの中の構成を変更
   - ./app/eventsディレクトリの中で必要ないものを削除
## 関連issue
   - #39 
## 結果画像
- ./admin(イベント・サービス 選択)
   <img src="https://github.com/user-attachments/assets/bb7a7dd4-b7a3-4126-aa32-b8b73afd0577" width="250">

- ./admin/events(新規イベント作成・既存ページ編集 選択)
  <img src="https://github.com/user-attachments/assets/118ed5a1-e56d-4b34-beca-9faa6a6cf36b" width="250">

- ./admin/event/existing-events(イベント一覧ページ)
  <img src="https://github.com/user-attachments/assets/9aaa1454-e672-4c5e-8702-806ad7d9d615" width="250">

- ./events(watnowユーザ以外イベント一覧画面)
  <img src="https://github.com/user-attachments/assets/b5e6426d-f513-4f1c-a599-e63fb2906773" width="250">

- ./events/'[event_id]'(watnowユーザ以外イベント詳細画面)
  <img src="https://github.com/user-attachments/assets/6ce914bb-6336-4fa8-b670-92a7418c38f0" width="250">

## 特にみて欲しい部分
   - 特になし
## 今回作れなかった部分
   - 特になし
## 補足
   - 僕のミスでコミットが見づらくなっているかもしれません、すいません！
   - ./app/eventsの確認はURLを直接入力する必要があります(SignUp, SignInが未実装なので)

2024-08-27 11:49 UTC, YukaChoco requested changes
だいぶなれてきてそうなので今更って言われそうだけどレビュー追加してマウス

2024-08-27 11:49 UTC, YukaChoco commented on src/app/admin/events/existing-events/[event_id]/edit/page.tsx
> +import LoadingSpinner from "../../../../components/LoadingSpinner";
せっかくなら@で統一しようか

2024-08-27 11:49 UTC, YukaChoco commented on src/app/admin/events/existing-events/[event_id]/edit/page.tsx
> +  const event_id: string = params.event_id as string;
こういうパラメータの受け取り方もあるよっていう提案と、なんとなく提案してる方に訂正してほしい感があるので、いろいろ参考に決めてみてください

https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes

`ChatGPTによる比較`
1. useParamsフックを使った受け取り方
```
const params = useParams();
const event_id: string = params.event_id as string;
```
- メリット
  - 柔軟性:
    - 複数のルートパラメータがある場合や、同一のコンポーネントを複数のルートで使う場合に適しています。
  - 使いやすさ:
    - useParamsフックを使えば、関数コンポーネント内で簡単にパラメータにアクセスできます。
  - 型推論:
    - パラメータの型が明示的ではないため、型定義を手動で行う必要がありますが、必要に応じて複数のパラメータを一度に取得できます。
- デメリット
  - 型安全性が低い:
    - パラメータの型が明示されないため、型安全性が低く、後で間違いが発生するリスクがあります。特にas stringのように型をアサーションする場合、実際の型が違ってもエラーが出ないため、バグの温床になりがちです。
  - 静的解析が難しい:
    - IDEや静的解析ツールが型を追跡しにくいため、誤ったパラメータ名の使用や、パラメータが存在しない場合でも気づきにくいです。
3. Propsとして受け取る方法
```
const UserPage = ({ params }: { params: { user_id: string } }) => {
  const userID = params.user_id;
・・・
};
```
- メリット
  - 型安全性:
    - パラメータの型を明示的に定義するため、型安全性が高く、コードの可読性が向上します。
  - 静的解析:
    - 型が明確に定義されているため、IDEや静的解析ツールがパラメータの使用に関するエラーを検出しやすいです。
  - テストのしやすさ:
    - テスト時にpropsをモックして、特定のパラメータでコンポーネントを簡単にテストできます。
- デメリット
  - 柔軟性の低下:
    - ルートパラメータが変更されるたびに、コンポーネントの定義も修正する必要があります。特に、複数のルートで同一のコンポーネントを使う場合には不便です。
  - 使い回しのしにくさ:
    - パラメータがpropsとして渡されるため、同じコンポーネントを別のコンテキストで使うときに不便です。

2024-08-27 11:49 UTC, YukaChoco commented on src/app/admin/events/existing-events/[event_id]/page.tsx
> +import LoadingSpinner from "../../../components/LoadingSpinner";
同じく＠にする(これ以降は表記しない)

2024-08-27 11:49 UTC, YukaChoco commented on src/app/admin/events/existing-events/[event_id]/page.tsx
> +import { Award } from "@/types/Award"
[FYI]
```
import type { EventDetail } from "@/types/Event";
```
みたいに型であることを明記してimportする記述方法もあるよ

2024-08-27 14:30 UTC, valen0306 commented on src/app/admin/events/existing-events/[event_id]/edit/page.tsx
> +  const event_id: string = params.event_id as string;
なるほどです！
僕も少し調べて、propsとして受け取る方法の方がいいと思ったのでuseParamsフックを使ってevent_idを取得していた箇所についてすべて変更しました！

2024-08-27 14:31 UTC, valen0306 commented on src/app/admin/events/existing-events/[event_id]/edit/page.tsx
> +import LoadingSpinner from "../../../../components/LoadingSpinner";
後のコミットでこの変更箇所については変更されていたみたいなのでコード中のすべての箇所について'@'をつかった表記に変更しました！

2024-08-28 06:54 UTC, YukaChoco requested changes
正直かなりコードがごちゃついてるので、関数を切り分けた方が良さそう、、、笑
考えるのめんどくさくてほっててごめんすぎる笑
次のPRあたりで分けよう。

2024-08-28 06:54 UTC, YukaChoco commented on src/app/admin/events/existing-events/[event_id]/edit/page.tsx
> +  const event_ID = params.event_id;
Reactの命名規則的には、`eventID` (キャメルケース)の方が良さそう
定義し直すくらいならReactに合わせちゃった方がいいんじゃないかな

2024-08-28 06:54 UTC, YukaChoco commented on src/app/admin/events/existing-events/[event_id]/page.tsx
> +import Link from "next/link";
未使用のものは削除しましょう〜

2024-08-28 06:54 UTC, YukaChoco commented on src/app/admin/events/existing-events/[event_id]/page.tsx
> +        </button>
Linkになってないぞ〜

2024-08-29 07:35 UTC, valen0306 commented on src/app/admin/events/existing-events/[event_id]/page.tsx
> +        </button>
変更がcommitされてなかったみたいです
watnowユーザのページはイベント詳細画面をとばして編集画面に遷移できるようにという話だったのでページを削除しました

2024-08-29 07:36 UTC, valen0306 commented
おそくなってすいません！
レビューお願いします！

2024-08-29 12:02 UTC, valen0306 commented
編集完了ボタンが押せないエラーについてなんですが、そのイベント以外はちゃんと押せるみたいです

エラーが発生している原因なんですが、supabaseのservicesテーブルのaward_idがawardsテーブルのidを参照していることで/editのhandleSaveClick中のupdateが制約を受けているからだと思うんですが、、、いったん参照の設定を削除しても大丈夫ですか？

2024-08-29 15:04 UTC, valen0306 commented
> いつからか定かじゃないですが、編集完了を押せません！！！

supabaseの設定を変更することで解消済みです！
servicesテーブルのaward_idがawardsテーブルのidを参照する設定になってたことでバグが起きてたみたいです

2024-08-31 13:21 UTC, YukaChoco requested changes
最後！！！！！

お願いしたい変更
- 編集完了後の遷移先をFigmaと同様に `/admin/events/existing-page` にする
  -  現状は一般人が見れる方の詳細画面に飛んでいる
  - おそらく編集完了した人は、続けて編集したい可能性が高いから

2024-08-31 13:32 UTC, YukaChoco approved these changes
長かったね笑
お疲れ様でした！！！！！！！！！！！！！！１

2024-08-31 13:51 UTC, merged