Feature/design eventlists
ikkei1616/watnowseikabutusite pull request #57
Opened 2024-09-10 13:38 UTC by valen0306

githubの操作が問題なかったか確かめるためのDraft pull requestです

2024-10-06 08:42 UTC, YukaChoco requested changes
お願いしたい変更点

- 画像の取得方法をカラムにあるパスそのまま使うように変更
  - 今は毎回getPublicUrlしてるけど、カラムに画像のURL突っ込んでしまって、それを表示する
  - おそらく型の修正とかもあるよね
- ローディングをちゃんと切り替える(ちゃんととは。不明)
- ページヘッダーの上の余白を増やす
  - ヘッダーとページのタイトルとの間のこと
- フォント当たってないとこ当てる
  - タグに直接font-family書いてあげればあたる

2024-11-19 11:06 UTC, YukaChoco requested changes
ページが下に下がっている状態でページネーションを切り替えてローディングのスケルトン表示される際に位置がバグるのでその修正

2024-11-20 02:25 UTC, valen0306 commented
スケルトン表示の際に位置がバグることの修正完了

今後必要になるであろう修正
・dateがnullのときの処理の追加(新規イベント登録の際のバリデーションも必要)
・イベント数の取得とイベントの取得を同時にする
・クライアントから直接supabaseをたたかないようにする

2024-11-21 05:04 UTC, YukaChoco approved these changes
LGTM！！！！

レスポンシブ対応して欲しいけど👀

2024-11-21 05:06 UTC, merged