Feature/event detail all products
ikkei1616/watnowseikabutusite pull request #78
Opened 2024-11-26 09:29 UTC by ikkei1616

## 実装内容
   - 各イベントのサービス一覧 
## 関連issue
   - (例：#11)
## 結果画像
   - 
<img width="1440" alt="スクリーンショット 2024-11-26 18 21 36" src="https://github.com/user-attachments/assets/de761c88-b628-46ca-8e3e-58b020411b74">

## 特にみて欲しい部分
   - 
## 今回作れなかった部分
   - ヘッダーのレスポンシブ対応
<img width="1440" alt="スクリーンショット 2024-11-26 18 21 43" src="https://github.com/user-attachments/assets/e342b5a5-ef97-4ac5-b775-820eb8be8b23">

## 質問
   -受賞した賞ごとにサービスカードのデザインを変えたほうがいいですか？
   -受賞した賞ごとにサービスカードの段落を変えたほうがいいですか?

2024-11-27 06:56 UTC, ikkei1616 commented
[
<img width="1440" alt="スクリーンショット 2024-11-26 18 21 36" src="https://github.com/user-attachments/assets/db0eab4d-ef6e-4ab2-ae7b-833b57008c22">
](url)

修正加えましたーーー

2024-11-27 06:56 UTC, ikkei1616 commented
修正加えました〜〜
![Uploading スクリーンショット 2024-11-27 15.55.49.png…]()

2024-11-27 06:58 UTC, ikkei1616 commented
<img width="1440" alt="スクリーンショット 2024-11-27 15 55 49" src="https://github.com/user-attachments/assets/2f2cc777-6cf1-45aa-b422-ab7be5d5915c">


修正しました〜〜！！

2025-01-30 07:30 UTC, YukaChoco reviewed
直して欲しい
- イベントが存在しない時のエラー画面表示
- イベントが存在してサービスが存在しないときに登録されてませんのエラー
- 下の余白追加
- イベント詳細画面へリンクのホバー追加

2025-02-03 02:01 UTC, YukaChoco requested changes
サービスない時の画像がめっちゃめっちゃいい感じ！
<img width="1470" alt="スクリーンショット 2025-02-03 10 57 58" src="https://github.com/user-attachments/assets/ec5eebf3-e13c-47e7-bd0c-e0f34b72c8a1" />



### お願いしたい修正点
- もうもう少し下の余白を増やしてほしい
<img width="300" alt="スクリーンショット 2025-02-03 10 59 18" src="https://github.com/user-attachments/assets/b915db7a-c26a-4c39-b2a4-d4a201f6652e" />

- このPRに含めるのは微妙だけど、サービス一覧画面のコメントが見えないのを修正

2025-02-10 00:44 UTC, YukaChoco approved these changes
動作確認OK

下記対応は時間がなかったので私が対応しました〜
- ServiceAwardCardをServiceCardに統一
- コメントじゃなくてdescriptionが表示されていたのでcommentに修正

2025-02-10 00:44 UTC, merged